Update requested_reviewers.yml

diff --git a/.github/workflows/requested_reviewers.yml b/.github/workflows/requested_reviewers.yml
--- a/.github/workflows/requested_reviewers.yml
+++ b/.github/workflows/requested_reviewers.yml
@@ -32,3 +32,14 @@ jobs:
             -H "Accept: application/vnd.github+json" \
             https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER/requested_reviewers \
             -d "{\"reviewers\": $REVIEWERS, \"team_reviewers\": $TEAM_REVIEWERS}")
+
+             # Capturar código de estado de la API
+          STATUS_CODE=$(cat response.json | jq -r '.message // empty')
+
+          # Verificar si los revisores se asignaron correctamente
+          if [ "$STATUS_CODE" == "null" ]; then
+            echo "Added reviewers to PR #$PR_NUMBER: jbustillolorenzo, yiramirez"
+          else
+            echo "Error assigning reviewers: $(cat response.json)"
+            exit 1
+          fi
